- name: install snmp
  hosts: 192.168.1.225
  tasks:
    - name: install Blender and Vlc 
      apt:
         name:
         - blender
         - vlc
         state:  present
         update_cache: true
      become: true
      when: ansible_os_family == 'Debian'
