- name: snmp firwall
  hosts: 192.168.1.225
  become: true

  tasks:
    - name: open firwall Ports 
      firewalld:
          port: 161
          state: enable
          source: 192.168.1.243

# or > shell : ufw allow from 192.168.1.243 to any port 161
